# Generated by Django 2.2.4 on 2019-08-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawler_tables',
            name='updated_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crawler_tables',
            name='working_while',
            field=models.CharField(max_length=20),
        ),
    ]
